spring.application.name=BloodBank

#MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/BloodBank_API
spring.datasource.username=root
spring.datasource.password=Jaideepak@18

# JPA/Hibernate orm
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true

#server Port
server.port=8080